# SSL证书配置
ssl:
  email: "admin@example.com"
  ca_server: "letsencrypt"  # 或 "zerossl", "buypass"
  key_length: 2048
  auto_upgrade: true
  
# acme.sh 配置
acme:
  staging: false  # 生产环境设为false
  force: false
  debug: false
  
# 证书颁发机构配置
ca_servers:
  letsencrypt:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    staging_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
  zerossl:
    server: "https://acme.zerossl.com/v2/DV90"
  buypass:
    server: "https://api.buypass.com/acme/directory"
    staging_server: "https://api.test4.buypass.no/acme/directory"

# 高级配置
advanced:
  # 证书更新检查间隔（小时）
  renewal_check_interval: 24
  # 证书过期前多少天开始更新
  renewal_days_before_expiry: 30
  # 并发申请证书数量限制
  concurrent_cert_limit: 3
  # 申请失败重试次数
  retry_attempts: 3
  # 重试间隔（秒）
  retry_interval: 300 