# 虚拟主机配置示例（简化格式）
# 测试配置 - 只包含静态文件服务

# 默认静态网站
- name: "default"
  domains:
    - "localhost"
    - "127.0.0.1"
  type: "static"
  root: "/var/www/html"
  ssl: false

# 示例静态网站（不启用SSL以避免证书问题）
- name: "static-site"
  domains:
    - "blog.example.com"
  type: "static"
  root: "/var/www/html"
  ssl: false 